"""some change in project

Revision ID: cf5868e397a0
Revises: 
Create Date: 2024-06-26 16:27:07.506196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5868e397a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CategoryInfo',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OtpInfo',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('otp', sa.String(length=50), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserInfo',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('u_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_no', sa.String(length=15), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NotificationInfo',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('recipient', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('u_id', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('reminder_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TodoInfo',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=100), nullable=False),
    sa.Column('priority_No', sa.String(length=100), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('u_id', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['CategoryInfo.id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TodoInfo')
    op.drop_table('NotificationInfo')
    op.drop_table('UserInfo')
    op.drop_table('OtpInfo')
    op.drop_table('CategoryInfo')
    # ### end Alembic commands ###
